-- Generated by: npm run generate:consonants
-- Run in Supabase SQL Editor to sync letter deck with data/thai-consonants.csv
-- Inserts missing letters; updates explanations and difficulty for existing ones.

insert into public.cards (deck_id, type, prompt_text, answer_text, explanation, difficulty)
select d.id, 'letter', v.prompt_text, v.answer_text, v.explanation, v.difficulty
from public.decks d
cross join (
  values
    ('ก', 'ก', 'ก — กไก่ (Chicken)', 1),
    ('ข', 'ข', 'ข — ขไข่ (Egg)', 1),
    ('ฃ', 'ฃ', 'ฃ — ฃขวด (Bottle)', 2),
    ('ค', 'ค', 'ค — ค ควาย (Water Buffalo)', 1),
    ('ฅ', 'ฅ', 'ฅ — ฅ คน (Person)', 2),
    ('ฆ', 'ฆ', 'ฆ — ฆ ระฆัง (Temple Bell)', 2),
    ('ง', 'ง', 'ง — ง งู (Snake)', 1),
    ('จ', 'จ', 'จ — จ จาน (Plate)', 1),
    ('ฉ', 'ฉ', 'ฉ — ฉ ฉิ่ง (Small Cymbal)', 2),
    ('ช', 'ช', 'ช — ช ช้าง (Elephant)', 1),
    ('ซ', 'ซ', 'ซ — ซ โซ่ (Chain for Animals)', 1),
    ('ฌ', 'ฌ', 'ฌ — ฌ เฌอ (Small Tree)', 2),
    ('ญ', 'ญ', 'ญ — ญ หญิง (Woman)', 2),
    ('ฎ', 'ฎ', 'ฎ — ฎ ชฎา (Dance Hat)', 2),
    ('ฏ', 'ฏ', 'ฏ — ฏ ปฏัก (Harpoon)', 2),
    ('ฐ', 'ฐ', 'ฐ — ฐ ฐาน (Pedestal)', 2),
    ('ฑ', 'ฑ', 'ฑ — ฑ มณโฑ (Ramayana Character)', 2),
    ('ฒ', 'ฒ', 'ฒ — ฒ ผู้เฒ่า (Old Man)', 2),
    ('ณ', 'ณ', 'ณ — ณ เณร (Buddhist Monk)', 2),
    ('ด', 'ด', 'ด — ด เด็ก (Child)', 1),
    ('ต', 'ต', 'ต — ต เต่า (Turtle)', 1),
    ('ถ', 'ถ', 'ถ — ถ ถุง (Shopping Bag)', 2),
    ('ท', 'ท', 'ท — ท ทหาร (Soldier)', 1),
    ('ธ', 'ธ', 'ธ — ธ ธง (Flag)', 2),
    ('น', 'น', 'น — น หนู (Mouse)', 1),
    ('บ', 'บ', 'บ — บ ใบไม้ (Leaf)', 1),
    ('ป', 'ป', 'ป — ป ปลา (Fish)', 1),
    ('ผ', 'ผ', 'ผ — ผ ผึ้ง (Bee)', 2),
    ('ฝ', 'ฝ', 'ฝ — ฝ ฝา (Lid)', 2),
    ('พ', 'พ', 'พ — พ พาน (Offering Tray)', 1),
    ('ฟ', 'ฟ', 'ฟ — ฟ ฟัน (Tooth)', 2),
    ('ภ', 'ภ', 'ภ — ภ สำเภา (Small Chinese Boat)', 2),
    ('ม', 'ม', 'ม — ม ม้า (Horse)', 1),
    ('ย', 'ย', 'ย — ย ยักษ์ (Demon / Giant)', 1),
    ('ร', 'ร', 'ร — ร เรือ (Boat)', 1),
    ('ล', 'ล', 'ล — ล ลิง (Monkey)', 1),
    ('ว', 'ว', 'ว — ว แหวน (Ring)', 1),
    ('ศ', 'ศ', 'ศ — ศ ศาลา (Gazebo / Pavilion)', 2),
    ('ษ', 'ษ', 'ษ — ษ ฤๅษี (Hermit)', 2),
    ('ส', 'ส', 'ส — ส เสือ (Tiger)', 1),
    ('ห', 'ห', 'ห — ห หีบ (Box / Trunk)', 2),
    ('ฬ', 'ฬ', 'ฬ — ฬ จุฬา (Kite)', 2),
    ('อ', 'อ', 'อ — อ อ่าง (Tub / Bucket)', 1),
    ('ฮ', 'ฮ', 'ฮ — ฮ นกฮูก (Owl)', 2)
) as v(prompt_text, answer_text, explanation, difficulty)
where d.slug = 'letters'
  and not exists (
    select 1 from public.cards c
    where c.deck_id = d.id and c.prompt_text = v.prompt_text
  );

update public.cards c
set
  explanation = case c.prompt_text
    when 'ก' then 'ก — กไก่ (Chicken)'
    when 'ข' then 'ข — ขไข่ (Egg)'
    when 'ฃ' then 'ฃ — ฃขวด (Bottle)'
    when 'ค' then 'ค — ค ควาย (Water Buffalo)'
    when 'ฅ' then 'ฅ — ฅ คน (Person)'
    when 'ฆ' then 'ฆ — ฆ ระฆัง (Temple Bell)'
    when 'ง' then 'ง — ง งู (Snake)'
    when 'จ' then 'จ — จ จาน (Plate)'
    when 'ฉ' then 'ฉ — ฉ ฉิ่ง (Small Cymbal)'
    when 'ช' then 'ช — ช ช้าง (Elephant)'
    when 'ซ' then 'ซ — ซ โซ่ (Chain for Animals)'
    when 'ฌ' then 'ฌ — ฌ เฌอ (Small Tree)'
    when 'ญ' then 'ญ — ญ หญิง (Woman)'
    when 'ฎ' then 'ฎ — ฎ ชฎา (Dance Hat)'
    when 'ฏ' then 'ฏ — ฏ ปฏัก (Harpoon)'
    when 'ฐ' then 'ฐ — ฐ ฐาน (Pedestal)'
    when 'ฑ' then 'ฑ — ฑ มณโฑ (Ramayana Character)'
    when 'ฒ' then 'ฒ — ฒ ผู้เฒ่า (Old Man)'
    when 'ณ' then 'ณ — ณ เณร (Buddhist Monk)'
    when 'ด' then 'ด — ด เด็ก (Child)'
    when 'ต' then 'ต — ต เต่า (Turtle)'
    when 'ถ' then 'ถ — ถ ถุง (Shopping Bag)'
    when 'ท' then 'ท — ท ทหาร (Soldier)'
    when 'ธ' then 'ธ — ธ ธง (Flag)'
    when 'น' then 'น — น หนู (Mouse)'
    when 'บ' then 'บ — บ ใบไม้ (Leaf)'
    when 'ป' then 'ป — ป ปลา (Fish)'
    when 'ผ' then 'ผ — ผ ผึ้ง (Bee)'
    when 'ฝ' then 'ฝ — ฝ ฝา (Lid)'
    when 'พ' then 'พ — พ พาน (Offering Tray)'
    when 'ฟ' then 'ฟ — ฟ ฟัน (Tooth)'
    when 'ภ' then 'ภ — ภ สำเภา (Small Chinese Boat)'
    when 'ม' then 'ม — ม ม้า (Horse)'
    when 'ย' then 'ย — ย ยักษ์ (Demon / Giant)'
    when 'ร' then 'ร — ร เรือ (Boat)'
    when 'ล' then 'ล — ล ลิง (Monkey)'
    when 'ว' then 'ว — ว แหวน (Ring)'
    when 'ศ' then 'ศ — ศ ศาลา (Gazebo / Pavilion)'
    when 'ษ' then 'ษ — ษ ฤๅษี (Hermit)'
    when 'ส' then 'ส — ส เสือ (Tiger)'
    when 'ห' then 'ห — ห หีบ (Box / Trunk)'
    when 'ฬ' then 'ฬ — ฬ จุฬา (Kite)'
    when 'อ' then 'อ — อ อ่าง (Tub / Bucket)'
    when 'ฮ' then 'ฮ — ฮ นกฮูก (Owl)'
    else c.explanation
  end,
  difficulty = case c.prompt_text
    when 'ก' then 1
    when 'ข' then 1
    when 'ฃ' then 2
    when 'ค' then 1
    when 'ฅ' then 2
    when 'ฆ' then 2
    when 'ง' then 1
    when 'จ' then 1
    when 'ฉ' then 2
    when 'ช' then 1
    when 'ซ' then 1
    when 'ฌ' then 2
    when 'ญ' then 2
    when 'ฎ' then 2
    when 'ฏ' then 2
    when 'ฐ' then 2
    when 'ฑ' then 2
    when 'ฒ' then 2
    when 'ณ' then 2
    when 'ด' then 1
    when 'ต' then 1
    when 'ถ' then 2
    when 'ท' then 1
    when 'ธ' then 2
    when 'น' then 1
    when 'บ' then 1
    when 'ป' then 1
    when 'ผ' then 2
    when 'ฝ' then 2
    when 'พ' then 1
    when 'ฟ' then 2
    when 'ภ' then 2
    when 'ม' then 1
    when 'ย' then 1
    when 'ร' then 1
    when 'ล' then 1
    when 'ว' then 1
    when 'ศ' then 2
    when 'ษ' then 2
    when 'ส' then 1
    when 'ห' then 2
    when 'ฬ' then 2
    when 'อ' then 1
    when 'ฮ' then 2
    else c.difficulty
  end
from public.decks d
where c.deck_id = d.id
  and d.slug = 'letters'
  and c.type = 'letter';
