-- Generated by: npm run generate:consonants
-- Run in Supabase SQL Editor to sync letter deck with data/thai-consonants.csv
-- Inserts missing letters; updates explanations and difficulty for existing ones.

insert into public.cards (deck_id, type, prompt_text, answer_text, explanation, difficulty)
select d.id, 'letter', v.prompt_text, v.answer_text, v.explanation, v.difficulty
from public.decks d
cross join (
  values
    ('ก', 'ก', 'ก — gaaw gài (Chicken)', 1),
    ('ข', 'ข', 'ข — khǎaw khài (Egg)', 1),
    ('ฃ', 'ฃ', 'ฃ — khǎaw khùuat (Bottle)', 2),
    ('ค', 'ค', 'ค — khaaw khwaai (Water Buffalo)', 1),
    ('ฅ', 'ฅ', 'ฅ — khaaw khon (Person)', 2),
    ('ฆ', 'ฆ', 'ฆ — khaaw rá-khang (Temple Bell)', 2),
    ('ง', 'ง', 'ง — ngaaw nguu (Snake)', 1),
    ('จ', 'จ', 'จ — jaaw jaan (Plate)', 1),
    ('ฉ', 'ฉ', 'ฉ — chǎaw chìng (Small Cymbal)', 2),
    ('ช', 'ช', 'ช — chaaw cháang (Elephant)', 1),
    ('ซ', 'ซ', 'ซ — saaw sôo (Chain for Animals)', 1),
    ('ฌ', 'ฌ', 'ฌ — chaaw chuuhr (Small Tree)', 2),
    ('ญ', 'ญ', 'ญ — yaaw yǐng (Woman)', 2),
    ('ฎ', 'ฎ', 'ฎ — daaw chá-daa (Dance Hat)', 2),
    ('ฏ', 'ฏ', 'ฏ — dtaaw bpà-dtàk (Harpoon)', 2),
    ('ฐ', 'ฐ', 'ฐ — thǎaw thǎan (Pedestal)', 2),
    ('ฑ', 'ฑ', 'ฑ — thaaw mon-thoo (Ramayana Character)', 2),
    ('ฒ', 'ฒ', 'ฒ — thaaw phûu-thâo (Old Man)', 2),
    ('ณ', 'ณ', 'ณ — naaw neen (Buddhist Monk)', 2),
    ('ด', 'ด', 'ด — daaw dèk (Child)', 1),
    ('ต', 'ต', 'ต — dtaaw dtào (Turtle)', 1),
    ('ถ', 'ถ', 'ถ — thǎaw thǔng (Shopping Bag)', 2),
    ('ท', 'ท', 'ท — thaaw thá-hǎan (Soldier)', 1),
    ('ธ', 'ธ', 'ธ — thaaw thong (Flag)', 2),
    ('น', 'น', 'น — naaw nǔu (Mouse)', 1),
    ('บ', 'บ', 'บ — baaw bai-máai (Leaf)', 1),
    ('ป', 'ป', 'ป — bpaaw bplaa (Fish)', 1),
    ('ผ', 'ผ', 'ผ — phǎaw phûeng (Bee)', 2),
    ('ฝ', 'ฝ', 'ฝ — fǎaw fǎa (Lid)', 2),
    ('พ', 'พ', 'พ — phaaw phaan (Offering Tray)', 1),
    ('ฟ', 'ฟ', 'ฟ — faaw fan (Tooth)', 2),
    ('ภ', 'ภ', 'ภ — phaaw sǎm phao (Small Chinese Boat)', 2),
    ('ม', 'ม', 'ม — maaw máa (Horse)', 1),
    ('ย', 'ย', 'ย — yaaw yák (Demon / Giant)', 1),
    ('ร', 'ร', 'ร — raaw ruuea (Boat)', 1),
    ('ล', 'ล', 'ล — laaw ling (Monkey)', 1),
    ('ว', 'ว', 'ว — waaw wǎaen (Ring)', 1),
    ('ศ', 'ศ', 'ศ — sǎaw sǎa-laa (Gazebo / Pavilion)', 2),
    ('ษ', 'ษ', 'ษ — sǎaw ruue-sǐi (Hermit)', 2),
    ('ส', 'ส', 'ส — sǎaw sǔuea (Tiger)', 1),
    ('ห', 'ห', 'ห — hǎaw hìip (Box / Trunk)', 2),
    ('ฬ', 'ฬ', 'ฬ — laaw jù-laa (Kite)', 2),
    ('อ', 'อ', 'อ — aaw àang (Tub / Bucket)', 1),
    ('ฮ', 'ฮ', 'ฮ — haaw nók-hûuk (Owl)', 2)
) as v(prompt_text, answer_text, explanation, difficulty)
where d.slug = 'letters'
  and not exists (
    select 1 from public.cards c
    where c.deck_id = d.id and c.prompt_text = v.prompt_text
  );

update public.cards c
set
  explanation = case c.prompt_text
    when 'ก' then 'ก — gaaw gài (Chicken)'
    when 'ข' then 'ข — khǎaw khài (Egg)'
    when 'ฃ' then 'ฃ — khǎaw khùuat (Bottle)'
    when 'ค' then 'ค — khaaw khwaai (Water Buffalo)'
    when 'ฅ' then 'ฅ — khaaw khon (Person)'
    when 'ฆ' then 'ฆ — khaaw rá-khang (Temple Bell)'
    when 'ง' then 'ง — ngaaw nguu (Snake)'
    when 'จ' then 'จ — jaaw jaan (Plate)'
    when 'ฉ' then 'ฉ — chǎaw chìng (Small Cymbal)'
    when 'ช' then 'ช — chaaw cháang (Elephant)'
    when 'ซ' then 'ซ — saaw sôo (Chain for Animals)'
    when 'ฌ' then 'ฌ — chaaw chuuhr (Small Tree)'
    when 'ญ' then 'ญ — yaaw yǐng (Woman)'
    when 'ฎ' then 'ฎ — daaw chá-daa (Dance Hat)'
    when 'ฏ' then 'ฏ — dtaaw bpà-dtàk (Harpoon)'
    when 'ฐ' then 'ฐ — thǎaw thǎan (Pedestal)'
    when 'ฑ' then 'ฑ — thaaw mon-thoo (Ramayana Character)'
    when 'ฒ' then 'ฒ — thaaw phûu-thâo (Old Man)'
    when 'ณ' then 'ณ — naaw neen (Buddhist Monk)'
    when 'ด' then 'ด — daaw dèk (Child)'
    when 'ต' then 'ต — dtaaw dtào (Turtle)'
    when 'ถ' then 'ถ — thǎaw thǔng (Shopping Bag)'
    when 'ท' then 'ท — thaaw thá-hǎan (Soldier)'
    when 'ธ' then 'ธ — thaaw thong (Flag)'
    when 'น' then 'น — naaw nǔu (Mouse)'
    when 'บ' then 'บ — baaw bai-máai (Leaf)'
    when 'ป' then 'ป — bpaaw bplaa (Fish)'
    when 'ผ' then 'ผ — phǎaw phûeng (Bee)'
    when 'ฝ' then 'ฝ — fǎaw fǎa (Lid)'
    when 'พ' then 'พ — phaaw phaan (Offering Tray)'
    when 'ฟ' then 'ฟ — faaw fan (Tooth)'
    when 'ภ' then 'ภ — phaaw sǎm phao (Small Chinese Boat)'
    when 'ม' then 'ม — maaw máa (Horse)'
    when 'ย' then 'ย — yaaw yák (Demon / Giant)'
    when 'ร' then 'ร — raaw ruuea (Boat)'
    when 'ล' then 'ล — laaw ling (Monkey)'
    when 'ว' then 'ว — waaw wǎaen (Ring)'
    when 'ศ' then 'ศ — sǎaw sǎa-laa (Gazebo / Pavilion)'
    when 'ษ' then 'ษ — sǎaw ruue-sǐi (Hermit)'
    when 'ส' then 'ส — sǎaw sǔuea (Tiger)'
    when 'ห' then 'ห — hǎaw hìip (Box / Trunk)'
    when 'ฬ' then 'ฬ — laaw jù-laa (Kite)'
    when 'อ' then 'อ — aaw àang (Tub / Bucket)'
    when 'ฮ' then 'ฮ — haaw nók-hûuk (Owl)'
    else c.explanation
  end,
  difficulty = case c.prompt_text
    when 'ก' then 1
    when 'ข' then 1
    when 'ฃ' then 2
    when 'ค' then 1
    when 'ฅ' then 2
    when 'ฆ' then 2
    when 'ง' then 1
    when 'จ' then 1
    when 'ฉ' then 2
    when 'ช' then 1
    when 'ซ' then 1
    when 'ฌ' then 2
    when 'ญ' then 2
    when 'ฎ' then 2
    when 'ฏ' then 2
    when 'ฐ' then 2
    when 'ฑ' then 2
    when 'ฒ' then 2
    when 'ณ' then 2
    when 'ด' then 1
    when 'ต' then 1
    when 'ถ' then 2
    when 'ท' then 1
    when 'ธ' then 2
    when 'น' then 1
    when 'บ' then 1
    when 'ป' then 1
    when 'ผ' then 2
    when 'ฝ' then 2
    when 'พ' then 1
    when 'ฟ' then 2
    when 'ภ' then 2
    when 'ม' then 1
    when 'ย' then 1
    when 'ร' then 1
    when 'ล' then 1
    when 'ว' then 1
    when 'ศ' then 2
    when 'ษ' then 2
    when 'ส' then 1
    when 'ห' then 2
    when 'ฬ' then 2
    when 'อ' then 1
    when 'ฮ' then 2
    else c.difficulty
  end
from public.decks d
where c.deck_id = d.id
  and d.slug = 'letters'
  and c.type = 'letter';
